
<a id="Import"></a>
# <p style="text-align:center; "> About || Data  </p>

### Context
This classic dataset contains the prices and other attributes of almost 54,000 diamonds. It's a great dataset for beginners learning to work with data analysis and visualization.

### Content
- **price**: Price in US dollars (\$326--\$18,823)
- **carat**: Weight of the diamond (0.2--5.01)
- **cut**: Quality of the cut (Fair, Good, Very Good, Premium, Ideal)
- **color**: Diamond colour, from J (worst) to D (best)
- **clarity**: A measurement of how clear the diamond is (I1 (worst), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (best))
- **x**: Length in mm (0--10.74)
- **y**: Width in mm (0--58.9)
- **z**: Depth in mm (0--31.8)
- **depth**: Total depth percentage = z / mean(x, y) = 2 * z / (x + y) (43--79)
- **table**: Width of top of diamond relative to widest point (43--95)

<a id="Import"></a>
# <p style="text-align:center; "> Import || Utilizs  </p>

In [ ]:
# Import Libraries
import tensorflow
from keras.layers import Dense
from tensorflow.keras.regularizers import l1, l2
from keras.models import Sequential
# Preprocessing 
from sklearn.preprocessing import MinMaxScaler , LabelEncoder , StandardScaler , QuantileTransformer
#Import Os and Basis Libraries
import cv2
import os
import shutil
import pandas as pd
import numpy as np
import seaborn as sns
from PIL import Image
from colorama import Fore, Style, init;
# Import necessary libraries
from IPython.display import display, HTML
import matplotlib.pyplot as plt 
import plotly.graph_objects as go
#Matplot Images
import matplotlib.image as mpimg
# Tensflor and Keras Layer and Model and Optimize and Loss
import tensorflow as tf
from pathlib import Path
import imghdr
import tensorflow_hub as hub
from tensorflow import keras
from keras import Sequential
from keras.layers import *
from tensorflow.keras.losses import BinaryCrossentropy
#Kernel Intilizer 
from sklearn.preprocessing import LabelEncoder
# import tensorflow_hub as hub
from tensorflow.keras.optimizers import Adam , Adamax
#PreTrained Model
from tensorflow.keras.applications import *
#Early Stopping
from tensorflow.keras.callbacks import EarlyStopping
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
# Warnings Remove 
import warnings 
warnings.filterwarnings("ignore")
# paellet 
palette = ["skyblue", "#FFDAB9"]
print_boxed_zigzag_heading('Setup Intilized')

<a id="Import"></a>
# <p style="text-align:center;">Overview || Data  </p>

In [ ]:
# Data
tr_d = sns.load_dataset('diamonds')
print_boxed_zigzag_heading('Data Loaded')

In [ ]:
# Function 4 Data Overview
def print_boxed_blue_heading(heading):
    gradient = [Fore.BLUE, Fore.CYAN, Fore.GREEN, Fore.YELLOW, Fore.RED, Fore.MAGENTA]
    print("\n" + "=" * (len(heading) + 20))
    words = heading.split()
    for i, word in enumerate(words):
        if i == len(words) - 1:
            print(f"| {gradient[len(word) % len(gradient)] + word + Style.RESET_ALL} |")
        else:
            print(f"| {gradient[len(word) % len(gradient)] + word + Style.RESET_ALL}", end=" ")
    print("=" * (len(heading) + 20))

# Main Heading    
def print_boxed_zigzag_heading(heading):
    gradient = [Fore.BLUE, Fore.CYAN, Fore.GREEN, Fore.YELLOW, Fore.RED, Fore.MAGENTA]
    print("\n" + f"{Fore.YELLOW}" + "╭" + "─" * (len(heading) + 20) + "╮" + Style.RESET_ALL)  # Change line color to yellow
    words = heading.split()
    for i, word in enumerate(words):
        if i == len(words) - 1:
            print(f"{Fore.CYAN}│ {word} │" + Style.RESET_ALL) 
        else:
            print(f"{gradient[len(word) % len(gradient)]}│ {word}", end=" ")
    print(f"{Fore.YELLOW}" + "╰" + "─" * (len(heading) + 20) + "╯" + Style.RESET_ALL) 

def print_error(message):
    raise ValueError(message)

def D_O(train_df):
    try:
        print_boxed_zigzag_heading('Train Data Overview')
        # Display head of the training dataset nicely
        print_boxed_blue_heading("The Head Of Train Dataset is:")
        display(HTML(train_df.head(5).to_html(index=False).replace('<table border="1" class="dataframe">', '<table style="border: 2px solid blue;">').replace('<td>', '<td style="color: skyblue;">')))
        print('\n')

        # Display tail of the training dataset nicely
        print_boxed_blue_heading("The Tail Of Train Dataset is:")
        display(HTML(train_df.tail(5).to_html(index=False).replace('<table border="1" class="dataframe">', '<table style="border: 2px solid blue;">').replace('<td>', '<td style="color: skyblue;">')))
        print('\n')

        print_boxed_blue_heading("Shape Data:")
        print(f'The Shape of the Train Data is {train_df.shape} |')
        print(f'- 1.The No of Rows is {train_df.shape[0]} |')
        print(f'- 2.The No of Cols is {train_df.shape[1]}|')
        
        print('\n')
        
        print_boxed_blue_heading("Info Of Train Data:")
        train_df.info()

        # Describe both numerical and categorical data
        print_boxed_blue_heading("Numerical Summary of Train Data:")
        print(f"\n{Style.BRIGHT + Fore.LIGHTBLUE_EX}The Numerical Summary of Train Data is:{Style.RESET_ALL}")
        display(train_df.describe().style.set_caption("Train Data Summary").set_table_styles([{'selector': 'caption', 'props': [('color', 'skyblue')]}]))

        Cat_cols_train = [col for col in train_df.columns if train_df[col].dtype == 'category']
        print_boxed_blue_heading("Categorical Columns of Train Data:")
        print(f'\n{Style.BRIGHT + Fore.LIGHTBLUE_EX}The Categorical Columns of Train Data are :{Style.RESET_ALL} {Cat_cols_train}')

        N_cols_train = [col for col in train_df.columns if train_df[col].dtype != 'category']
        print_boxed_blue_heading("Numerical Columns of Train Data:")
        print(f'\n{Style.BRIGHT + Fore.LIGHTBLUE_EX}The Numerical Columns of Train Data are :{Style.RESET_ALL} {N_cols_train}\n')

        print_boxed_blue_heading("Null Values in Train Data:")
        print(f'\n{Style.BRIGHT + Fore.LIGHTBLUE_EX}The Null Values of Train Data are:{Style.RESET_ALL}\n{train_df.isnull().sum()}')

        print_boxed_blue_heading("Duplicates Check in Train Data:")
        if train_df.duplicated().any():
            print(f'\n{Style.BRIGHT + Fore.LIGHTBLUE_EX}Duplicates exist in the train dataset.{Style.RESET_ALL}')
        else:
            print(f'\n{Style.BRIGHT + Fore.LIGHTBLUE_EX}No duplicates found in the train dataset.{Style.RESET_ALL}')

        print('\n' + "=" * 100 + '\n')
        
    except Exception as e:
        print_error(f"An error occurred: {str(e)}")

In [ ]:
# Overview
D_O(tr_d)

In [ ]:
# Dropping Duplicates 
tr_d.drop_duplicates(inplace=True)

<a id="Import"></a>
# <p style="text-align:center;"> EDA || Visualizations   </p>

In [ ]:
# Cut Counts 
single_plot_distribution('cut',tr_d)

In [ ]:
# Color Counts 
single_plot_distribution('color',tr_d)

In [ ]:
# Clarity Counts 
single_plot_distribution('clarity',tr_d)

In [ ]:
# Function to Plot Hist and Box
def plot_histograms_and_boxplots(data, columns, color='#FF7F50'):
    num_plots = len(columns)
    fig, axes = plt.subplots(num_plots, 2, figsize=(15, num_plots*5))
    
    for i, col in enumerate(columns):
        sns.histplot(data[col], ax=axes[i, 0], color=color)
        axes[i, 0].set_title(f'Histogram of {col}')
        
        sns.boxplot(data[col], ax=axes[i, 1], color=color)
        axes[i, 1].set_title(f'Boxplot of {col}')
        
    plt.tight_layout()
    plt.show()
    
# Plot 
print_boxed_zigzag_heading('Numerical features')
plot_histograms_and_boxplots(tr_d,['carat','depth', 'table', 'price', 'x', 'y',
       'z'])

In [ ]:
# Remove Outliers
def remove_outliers_iqr(df):
    # Selecting only float features
    float_columns = df.select_dtypes(include=['float64']).columns

    # Calculate first quartile (Q1)
    q1 = df[float_columns].quantile(0.25)
    # Calculate third quartile (Q3)
    q3 = df[float_columns].quantile(0.75)
    # Calculate IQR (Interquartile Range)
    iqr = q3 - q1

    # Identify outliers
    outlier_mask = ((df[float_columns] < (q1 - 1.5 * iqr)) | (df[float_columns] > (q3 + 1.5 * iqr)))
    # Count outliers in each column
    num_outliers = outlier_mask.sum()

    # Print the number of outliers
    print_boxed_zigzag_heading("Number of outliers detected:\n")
    print(num_outliers)
    
    # Remove outliers
    df_cleaned = df[~outlier_mask.any(axis=1)]

    # Count outliers after removal
    num_outliers_cleaned = ((df_cleaned[float_columns] < (q1 - 1.5 * iqr)) | (df_cleaned[float_columns] > (q3 + 1.5 * iqr))).sum()
    print_boxed_zigzag_heading("Number of outliers after removal:\n")
    print(num_outliers_cleaned)

    return df_cleaned

# Exceuting Function
tr_d = remove_outliers_iqr(tr_d)

<a id="Import"></a>
# <p style="text-align:center;"> Encoding || Features  </p>

In [ ]:
# Defining the categorical columns to encode
CAT_COL_E = ['cut','color','clarity']

# Function to encode columns using Label Encoding
def LabelEncode(data, columns):
    # Initialize LabelEncoder
    L_E = LabelEncoder()
    
    # Encode categorical columns
    for col in columns:
        data[col] = L_E.fit_transform(data[col])
    
    # Return the encoded data
    return data

# Encoder Train  
tr_d = LabelEncode(tr_d, CAT_COL_E)
print_boxed_zigzag_heading('Data is Encoded Successfully')

<a id="Import"></a>
# <p style="text-align:center;"> Model || Building  </p>

In [ ]:
# # # =================================================================================================================
# # #                         X < y 
# # #================================================================================================================== 
X_T = tr_d.drop('carat', axis=1)
y_T = tr_d['carat']

# # # =================================================================================================================
# # #                         Train < Test Split
# # #================================================================================================================== 
X_TR, X_TE, Y_TR, Y_TE = train_test_split(X_T, y_T, test_size=0.1, random_state=42)

# # # =================================================================================================================
# # #                         Scale Data 
# # #================================================================================================================== 
scaler = MinMaxScaler()
#USing Loop
for col in X_TR.columns:
    X_TR[col] = scaler.fit_transform(X_TR[[col]])
for col in X_TE.columns:
    X_TE[col] = scaler.fit_transform(X_TE[[col]])

# # # =================================================================================================================
# # #                         Shapes < 
# # #================================================================================================================== 
print_boxed_zigzag_heading(f"Training set shape - X: {X_TR.shape}, y: {Y_TR.shape}")
print_boxed_zigzag_heading(f"Testing set shape - X: {X_TE.shape}, y: {Y_TE.shape}")

In [ ]:
#Sequentail Model
model = Sequential()

#Imput Layer 
model.add(Dense(10,activation='relu',input_dim=9, kernel_regularizer=l1(0.01)))
#Hidden Layers 
model.add(Dense(10,activation='relu'))
#OutputLayer
model.add(Dense(1,activation='linear'))

#Compile
model.compile(loss='huber',optimizer='Adam',metrics='mse')

# Summary 
model.summary()

#Fit 
history = model.fit(X_TR,
                    Y_TR,
                    epochs=15,
                    validation_split=0.2)

<a id="Import"></a>
# <p style="text-align:center;"> Test || Predictions  </p>

In [ ]:
# Prediction
print_boxed_zigzag_heading('Predicting Test Data')
y_pred = model.predict(X_TE)

In [ ]:
# Evaluate R2
print_boxed_zigzag_heading(f'R2 Score Of Model is {r2_score(Y_TE,y_pred)}')

<a id="Import"></a>
# <p style="text-align:center;"> Loss || Test  </p>

In [ ]:
# Assuming history is the variable containing loss and validation loss data
print_boxed_zigzag_heading('Val Loss and Loss')
plt.figure(figsize=(20, 8)) 
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend()
plt.show()